(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const ML=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const CATS={logement:'Logement',transport:'Transport',alimentation:'Alimentation',abonnements:'Abonnements',enfants:'Enfants',credits:'Crédits',assurances:'Assurances',loisirs:'Loisirs',sante:'Santé',autres:'Autres'};
const CAT_ICONS={logement:'🏠',transport:'🚗',alimentation:'🛒',abonnements:'📱',enfants:'👶',credits:'💳',assurances:'🛡️',loisirs:'🎬',sante:'💊',autres:'📦'};
let state={page:'dashboard',cm:new Date().getMonth(),app:null};

function eur(v){let n=parseFloat(v)||0;return (n<0?'-':'')+Math.abs(n).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function short(v){let n=parseFloat(v)||0;return Math.abs(n)>=1000?(n<0?'-':'')+(Math.abs(n)/1000).toFixed(1).replace('.',',')+'k €':eur(n)}
function p2(n){return String(n).padStart(2,'0')}
function todayStr(){let d=new Date();return `${d.getFullYear()}-${p2(d.getMonth()+1)}-${p2(d.getDate())}`}
function dateFR(s){if(!s)return'Sans date';let p=s.split('-');return `${p[2]}/${p[1]}`}
function parseDate(s){if(!s)return null;let p=s.split('-');return new Date(+p[0],+p[1]-1,+p[2])}
function daysLeft(s){let b=parseDate(s);if(!b)return null;let a=new Date();a.setHours(0,0,0,0);b.setHours(0,0,0,0);return Math.round((b-a)/86400000)}
function monthKey(i){return new Date().getFullYear()+'-'+p2(i+1)}
function clone(x){return JSON.parse(JSON.stringify(x))}

function mkRow(n,a,d,c){return{name:n||'',amount:parseFloat(a)||0,paid:false,dueDate:d||'',paidDate:'',cat:c||'autres'}}
function defIncome(){let sal=mkRow('Salaire',0,'','autres');sal.auto=true;sal.paid=true;let sup=mkRow('Revenus supplémentaires',0,'','autres');return[sal,sup]}
function defExpenses(){return[mkRow('Logement',0,'','logement'),mkRow('Supermarché',0,'','alimentation'),mkRow('Assurance voiture',0,'','assurances'),mkRow('Essence',0,'','transport'),mkRow('Internet / Mobile',0,'','abonnements'),mkRow('Électricité',0,'','logement'),mkRow('Cantine enfants',0,'','enfants')]}
function defMonth(){return{income:defIncome(),expenses:defExpenses(),savings:{amount:0,paid:false,date:''}}}
function isAutoIncome(r){return !!(r&&r.auto)||/salaire|paie|pay/i.test((r&&r.name)||'')}
function guessCat(n){n=(n||'').toLowerCase();if(/loyer|pret|prêt|logement|electricit|électricit|gaz|eau/.test(n))return'logement';if(/voiture|essence|autoroute|parking/.test(n))return'transport';if(/supermarch|course|aliment|restaurant/.test(n))return'alimentation';if(/mobile|internet|freebox|netflix|spotify|apple|abonnement|chat/.test(n))return'abonnements';if(/cantine|ecole|enfant/.test(n))return'enfants';if(/credit|crédit|cetelem|natixis/.test(n))return'credits';if(/assurance|mutuelle/.test(n))return'assurances';return'autres'}
function fix(r){r.dueDate=r.dueDate||'';r.paidDate=r.paidDate||'';r.cat=r.cat||guessCat(r.name);r.amount=parseFloat(r.amount)||0;if(isAutoIncome(r)){r.auto=true;r.paid=true}else{r.paid=!!r.paid}}
function normalize(src){let d=src?clone(src):{currentMonth:new Date().getMonth(),months:{}};if(!d.months)d.months={};for(let i=0;i<12;i++){let m=d.months[i]||d.months[String(i)]||defMonth();m.income=m.income||defIncome();m.expenses=m.expenses||defExpenses();m.savings=m.savings||{amount:0,paid:false,date:''};m.income.forEach(fix);m.expenses.forEach(fix);m.savings.amount=parseFloat(m.savings.amount)||0;m.savings.paid=!!m.savings.paid;d.months[i]=m}if(!d.savings)d.savings={balance:0,target:50000,monthlyTarget:1000,history:{}};if(!d.savings.history)d.savings.history={};return d}
function load(){let raw=null;['bgt4','budgetV3','budgetV2'].some(k=>{try{raw=localStorage.getItem(k);return !!raw}catch(e){return false}});let data=null;try{data=raw?JSON.parse(raw):null}catch(e){};state.app=normalize(data);state.cm=Number.isInteger(state.app.currentMonth)?state.app.currentMonth:new Date().getMonth()}
function save(){state.app.currentMonth=state.cm;localStorage.setItem('bgt4',JSON.stringify(state.app));toast('Enregistré')}
function exportJSON(){return JSON.stringify(state.app,null,2)}

function m(){return state.app.months[state.cm]}
function totals(mi=state.cm){let mm=state.app.months[mi],tIn=0,tEx=0,pIn=0,pEx=0;mm.income.forEach(r=>{let v=+r.amount||0;tIn+=v;if(r.paid||isAutoIncome(r))pIn+=v});mm.expenses.forEach(r=>{let v=+r.amount||0;tEx+=v;if(r.paid)pEx+=v});return{tIn,tEx,pIn,pEx,remain:tIn-tEx,live:pIn-pEx,pct:tIn?Math.round(tEx/tIn*100):0}}
function dash(){let mm=m(),now=new Date();now.setHours(0,0,0,0);let solde=0,income=0,exTotal=0,aPayer=0,revFut=0;mm.income.forEach(r=>{let v=+r.amount||0;income+=v;if(r.paid||isAutoIncome(r))solde+=v;else revFut+=v});mm.expenses.forEach(r=>{let v=+r.amount||0;exTotal+=v;let d=parseDate(r.dueDate);if(r.paid)solde-=v;else if(d&&d>now)aPayer+=v;else if(!d&&!r.paid){}else solde-=v});return{solde,income,exTotal,aPayer,revFut,final:solde+revFut-aPayer,pct:income?Math.min(200,exTotal/income*100):0}}
function getSavCap(i=state.cm){let s=state.app.savings,k=monthKey(i);if(s.history&&s.history[k]!=null)return +s.history[k]||0;return +s.balance||0}
function savPct(){let cap=getSavCap(),target=+state.app.savings.target||0;return target?Math.min(100,Math.round(cap/target*100)):0}
function byCat(){let o={};m().expenses.forEach(r=>{o[r.cat||'autres']=(o[r.cat||'autres']||0)+(+r.amount||0)});return o}
function upcoming(limit=5){return m().expenses.filter(r=>!r.paid&&(+r.amount||0)>0&&r.dueDate).map(r=>({r,dl:daysLeft(r.dueDate),dt:parseDate(r.dueDate)})).filter(x=>x.dt).sort((a,b)=>a.dt-b.dt).slice(0,limit)}
function dailyFlow(){let days=new Date(new Date().getFullYear(),state.cm+1,0).getDate(),arr=[];for(let i=1;i<=days;i++)arr.push({d:i,bal:0,in:0,ex:0});m().income.forEach(r=>{if(+r.amount)arr[0].in+=(+r.amount||0)});m().expenses.forEach(r=>{let v=+r.amount||0;if(!v)return;let d=parseDate(r.dueDate);let day=d&&d.getMonth()===state.cm?d.getDate():1;arr[Math.max(0,Math.min(days-1,day-1))].ex+=v});let b=0;arr.forEach(x=>{b+=x.in-x.ex;x.bal=b});return arr}

function render(){ $('#monthLabel').textContent=ML[state.cm]+' '+new Date().getFullYear(); $$('.page').forEach(p=>p.classList.remove('active')); $('#page-'+state.page).classList.add('active'); $$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page)); if(state.page==='dashboard')renderDashboard(); if(state.page==='transactions')renderTransactions(); if(state.page==='stats')renderStats(); if(state.page==='goals')renderGoals(); if(state.page==='settings')renderSettings(); }
function sparkline(){let f=dailyFlow(),vals=f.map(x=>x.bal),min=Math.min(...vals,0),max=Math.max(...vals,1),pts=f.map((x,i)=>`${i*(300/(f.length-1))},${60-((x.bal-min)/(max-min||1))*54}`).join(' ');return `<svg viewBox="0 0 300 64" width="100%" height="64"><polyline fill="none" stroke="#22C55E" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" points="${pts}"/><polyline fill="none" stroke="rgba(34,197,94,.16)" stroke-width="14" stroke-linecap="round" stroke-linejoin="round" points="${pts}"/></svg>`}
function renderDashboard(){let d=dash(),t=totals(),cap=getSavCap(),sp=savPct(),ups=upcoming(4),ct=byCat(),topCat=Object.keys(ct).sort((a,b)=>ct[b]-ct[a])[0],advice=d.final<0?'Attention, fin de mois négative prévue.': t.pct>85?'Dépenses élevées ce mois-ci.':'Budget sous contrôle, continue comme ça.';$('#page-dashboard').innerHTML=`<div class="grid"><section class="card hero span-8"><div class="hero-top"><div><div class="eyebrow">Solde actuel</div><div class="hero-amount ${d.solde<0?'neg':''}">${eur(d.solde)}</div><p class="muted">Fin de mois estimée : <b class="${d.final<0?'neg':'positive'}">${eur(d.final)}</b></p></div><span class="chip ${d.final<0?'red':''}">${d.final<0?'À surveiller':'Stable'}</span></div><div class="mini-chart">${sparkline()}</div></section><section class="card kpi green span-4"><div class="kpi-icon">💰</div><h3>Épargne</h3><div class="value">${eur(cap)}</div><div class="progress"><div class="fill" style="width:${sp}%"></div></div><p class="muted">${sp}% de l’objectif</p></section><section class="card kpi blue span-3"><div class="kpi-icon">↗</div><h3>Revenus</h3><div class="value">${short(d.income)}</div><p class="muted">${eur(t.pIn)} comptés</p></section><section class="card kpi red span-3"><div class="kpi-icon">↘</div><h3>Dépenses</h3><div class="value">${short(d.exTotal)}</div><p class="muted">${eur(t.pEx)} confirmées</p></section><section class="card kpi purple span-3"><div class="kpi-icon">📌</div><h3>À payer</h3><div class="value">${short(d.aPayer)}</div><p class="muted">prélèvements futurs</p></section><section class="card kpi span-3"><div class="kpi-icon">%</div><h3>Taux budget</h3><div class="value">${Math.round(d.pct)}%</div><p class="muted">utilisation revenus</p></section><section class="card span-6"><h2 class="section-title">Prélèvements à venir</h2>${ups.length?ups.map(x=>lineExpense(x.r,true)).join(''):'<p class="muted">Aucun prélèvement prévu.</p>'}</section><section class="card span-6"><h2 class="section-title">Conseil ORION</h2><div class="alert-card"><span>✨</span><div><b>${advice}</b><p class="muted">${topCat?'Plus gros poste : '+(CATS[topCat]||topCat)+' · '+eur(ct[topCat]):'Ajoute tes dépenses pour obtenir une analyse.'}</p></div></div><div class="alert-card"><span>🎯</span><div><b>Objectif principal</b><p class="muted">Capital ${eur(cap)} sur ${eur(state.app.savings.target||0)}</p></div></div></section></div>`}
function lineExpense(r,checkbox=false){return `<div class="row"><button class="check ${r.paid?'on':''}" data-toggle-exp="${m().expenses.indexOf(r)}">✓</button><div class="row-main"><div class="row-title">${CAT_ICONS[r.cat]||'•'} ${escapeHtml(r.name)}</div><div class="row-sub">${r.paid?'Confirmé':'Prévu'} · ${dateFR(r.dueDate)}</div></div><div class="amount ${r.paid?'positive':''}">${eur(r.amount)}</div></div>`}
function renderTransactions(){let mm=m();$('#page-transactions').innerHTML=`<div class="card"><h2 class="section-title">Ajouter une ligne</h2><div class="form-line"><input id="newName" placeholder="Libellé"><input id="newAmount" type="number" placeholder="Montant"><input id="newDate" type="date"><select id="newType"><option value="expense">Dépense</option><option value="income">Revenu</option></select><button class="primary" id="addLine">Ajouter</button></div></div><div class="card table-card"><div class="between"><h2 class="section-title">Transactions</h2><select class="select-small" id="monthSelect">${ML.map((x,i)=>`<option value="${i}" ${i===state.cm?'selected':''}>${x}</option>`).join('')}</select></div><div class="tx-grid head"><div></div><div>Nom</div><div>Catégorie</div><div>Date</div><div>Montant</div><div></div></div>${mm.income.map((r,i)=>txRow(r,'income',i)).join('')}${mm.expenses.map((r,i)=>txRow(r,'expense',i)).join('')}</div>`}
function txRow(r,type,i){return `<div class="tx-grid"><button class="check ${r.paid||isAutoIncome(r)?'on':''}" data-toggle-${type==="income"?'inc':'exp'}="${i}">✓</button><div><b>${escapeHtml(r.name)}</b><div class="row-sub">${type==='income'?'Revenu':'Dépense'}</div></div><div>${CATS[r.cat]||'Autres'}</div><div>${dateFR(r.dueDate)}</div><div class="amount ${type==='income'?'positive':'neg'}">${type==='income'?'+':'-'}${eur(r.amount)}</div><button data-edit="${type}:${i}">✎</button></div>`}
function renderStats(){let t=totals(),ct=byCat(),max=Math.max(...Object.values(ct),1),prev=totals((state.cm+11)%12);$('#page-stats').innerHTML=`<div class="grid"><section class="card span-6"><h2 class="section-title">Répartition</h2><div class="bar-list">${Object.keys(ct).sort((a,b)=>ct[b]-ct[a]).map(k=>`<div class="bar-row"><b>${CATS[k]||k}</b><div class="bar-bg"><div class="bar" style="width:${ct[k]/max*100}%"></div></div><span>${short(ct[k])}</span></div>`).join('')}</div></section><section class="card span-6"><h2 class="section-title">Comparaison</h2><div class="alert-card"><span>📈</span><div><b>Ce mois : ${eur(t.remain)}</b><p class="muted">Mois précédent : ${eur(prev.remain)}</p></div></div><div class="alert-card"><span>💸</span><div><b>Dépenses : ${eur(t.tEx)}</b><p class="muted">Revenus : ${eur(t.tIn)}</p></div></div></section><section class="card span-12"><h2 class="section-title">Courbe du mois</h2>${sparkline()}</section></div>`}
function renderGoals(){let cap=getSavCap(),target=+state.app.savings.target||50000,items=[['🏡','Maison',target,cap],['🛡️','Fonds d’urgence',10000,Math.min(cap,10000)],['✈️','Voyage',3000,Math.min(cap*.18,3000)]];$('#page-goals').innerHTML=`<div class="grid">${items.map(g=>{let p=g[2]?Math.min(100,Math.round(g[3]/g[2]*100)):0;return `<section class="card goal-card span-4"><div class="goal-icon">${g[0]}</div><h2>${g[1]}</h2><p class="muted">${eur(g[3])} / ${eur(g[2])}</p><div class="progress"><div class="fill" style="width:${p}%"></div></div><b>${p}% atteint</b></section>`}).join('')}</div>`}
function renderSettings(){ $('#page-settings').innerHTML=`<div class="grid"><section class="card span-6"><h2 class="section-title">Données</h2><button class="primary" id="btnExport">Exporter JSON</button><br><br><textarea class="export-box" id="jsonBox" placeholder="Export / import JSON"></textarea><br><br><button class="secondary" id="btnImport">Importer JSON</button></section><section class="card span-6"><h2 class="section-title">Infos</h2><div class="alert-card"><span>✅</span><div><b>Compatibilité ancienne app</b><p class="muted">Lecture automatique de bgt4, budgetV3 et budgetV2.</p></div></div><div class="alert-card"><span>💾</span><div><b>Stockage local</b><p class="muted">Les données restent dans le navigateur.</p></div></div></section></div>` }
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function openEditor(type,i){let r= type==='income'?m().income[i]:m().expenses[i];$('#editType').value=type;$('#editIndex').value=i;$('#editName').value=r.name;$('#editAmount').value=r.amount;$('#editDate').value=r.dueDate||'';$('#editCat').innerHTML=Object.keys(CATS).map(k=>`<option value="${k}" ${k===r.cat?'selected':''}>${CATS[k]}</option>`).join('');$('#btnDelete').style.display=isAutoIncome(r)?'none':'';$('#editorSheet').classList.add('open');$('#sheetBackdrop').classList.add('show')}
function closeEditor(){$('#editorSheet').classList.remove('open');$('#sheetBackdrop').classList.remove('show')}
function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),10);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),200)},1800)}

document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){state.page=b.dataset.page;render()} if(b.id==='btnRefresh'){load();render();toast('Recalculé')} if(b.id==='addLine'){let type=$('#newType').value,row=mkRow($('#newName').value,$('#newAmount').value,$('#newDate').value,guessCat($('#newName').value)); if(!row.name)return toast('Nom obligatoire'); if(type==='income')m().income.push(row); else m().expenses.push(row); save();render()} if(b.dataset.toggleExp!=null){let r=m().expenses[+b.dataset.toggleExp];r.paid=!r.paid;r.paidDate=r.paid?todayStr():'';save();render()} if(b.dataset.toggleInc!=null){let r=m().income[+b.dataset.toggleInc];if(isAutoIncome(r))return toast('Salaire automatique');r.paid=!r.paid;save();render()} if(b.dataset.edit){let [type,i]=b.dataset.edit.split(':');openEditor(type,+i)} if(b.id==='btnCloseSheet')closeEditor(); if(b.id==='btnSaveLine'){let type=$('#editType').value,i=+$('#editIndex').value,r=type==='income'?m().income[i]:m().expenses[i];r.name=$('#editName').value;r.amount=parseFloat($('#editAmount').value)||0;r.dueDate=$('#editDate').value;r.cat=$('#editCat').value;save();closeEditor();render()} if(b.id==='btnDelete'){let type=$('#editType').value,i=+$('#editIndex').value;if(type==='income')m().income.splice(i,1);else m().expenses.splice(i,1);save();closeEditor();render()} if(b.id==='btnExport'){$('#jsonBox').value=exportJSON();toast('Export prêt')} if(b.id==='btnImport'){try{state.app=normalize(JSON.parse($('#jsonBox').value));save();render()}catch(err){toast('JSON invalide')}}});
document.addEventListener('change',e=>{if(e.target.id==='monthSelect'){state.cm=+e.target.value;state.app.currentMonth=state.cm;save();render()}});
$('#sheetBackdrop').addEventListener('click',closeEditor);
load();render();
})();
