(()=>{'use strict';
const ML=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const CATS={logement:'Logement',alimentation:'Alimentation',transport:'Transport',loisirs:'Loisirs',sante:'Santé',abonnements:'Abonnements',assurances:'Assurances',credits:'Crédits',enfants:'Enfants',autres:'Autres'};
const COLORS={logement:'#16a15b',alimentation:'#8b6aa8',transport:'#f39718',loisirs:'#f0b21d',sante:'#64b89f',abonnements:'#2781d8',assurances:'#4e8fe7',credits:'#ea6b2d',enfants:'#ee5d89',autres:'#5f8aa8'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], num=v=>Number.isFinite(+v)?+v:0, p2=n=>String(n).padStart(2,'0');
const eur=v=>num(v).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const iso=(y,m,d)=>`${y}-${p2(m+1)}-${p2(d)}`; const today=()=>{let d=new Date();return iso(d.getFullYear(),d.getMonth(),d.getDate())};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function safeParse(s,d){try{return JSON.parse(s)||d}catch{return d}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function migrateMonth(m){m=m||{};return {income:Array.isArray(m.income)?m.income:[],expenses:Array.isArray(m.expenses)?m.expenses:[],savings:m.savings||{amount:0,paid:false,date:''},meta:m.meta||{}}}
function loadBudget(){let raw=localStorage.getItem('bgt4')||localStorage.getItem('budgetV3')||localStorage.getItem('budgetV2');let d=safeParse(raw,{});if(!d||typeof d!=='object')d={};
 d.monthlyData=d.monthlyData||{}; if(!Object.keys(d.monthlyData).length&&d.years){Object.keys(d.years).forEach(y=>{let ms=d.years[y]?.months||{};Object.keys(ms).forEach(m=>d.monthlyData[`${y}-${p2(+m+1)}`]=migrateMonth(ms[m]))})}
 if(!Object.keys(d.monthlyData).length&&d.months){let y=d.currentYear||new Date().getFullYear();Object.keys(d.months).forEach(m=>d.monthlyData[`${y}-${p2(+m+1)}`]=migrateMonth(d.months[m]))}
 d.recurringTemplates=Array.isArray(d.recurringTemplates)?d.recurringTemplates:[]; return d}
let budget=loadBudget(); let extra=safeParse(localStorage.getItem('orion_plus_v4'),null)||safeParse(localStorage.getItem('orion_plus_v3'),{})||{};extra.birthdays=Array.isArray(extra.birthdays)?extra.birthdays:[];extra.exchanges=Array.isArray(extra.exchanges)?extra.exchanges:[];
let goals=safeParse(localStorage.getItem('orion_v21_goals'),[]);if(!Array.isArray(goals))goals=[];
let year=Number.isInteger(budget.currentYear)?budget.currentYear:new Date().getFullYear(), month=Number.isInteger(budget.currentMonth)?budget.currentMonth:new Date().getMonth(), page='home', txFilter='all';
const key=()=>`${year}-${p2(month+1)}`;
function backup(){if(!localStorage.getItem('orion_backup_before_v4')){let r=localStorage.getItem('bgt4');if(r)localStorage.setItem('orion_backup_before_v4',r)}}
function saveBudget(){backup();budget.currentYear=year;budget.currentMonth=month;budget.schema=Math.max(4,num(budget.schema));localStorage.setItem('bgt4',JSON.stringify(budget))}
function saveExtra(){localStorage.setItem('orion_plus_v4',JSON.stringify(extra))} function saveGoals(){localStorage.setItem('orion_v21_goals',JSON.stringify(goals))}
function monthObj(k=key()){if(!budget.monthlyData[k])budget.monthlyData[k]={income:[],expenses:[],savings:{amount:0,paid:false,date:''},meta:{generated:true}};generateTemplates(k);return budget.monthlyData[k]}
function monthsBetween(a,b){let A=a.slice(0,7).split('-').map(Number),B=b.slice(0,7).split('-').map(Number);return (B[0]-A[0])*12+B[1]-A[1]}
function occurrence(t,k){let sk=(t.startDate||'').slice(0,7);if(!sk||k<sk)return null;let e=monthsBetween(sk,k);if(t.endDate&&k>(t.endDate||'').slice(0,7))return null;if(t.freq==='once'&&e!==0)return null;if(t.freq==='everyN'&&e%Math.max(1,num(t.interval))!==0)return null;let i=t.freq==='everyN'?e/Math.max(1,num(t.interval)):e;if(num(t.installments)>0&&i>=num(t.installments))return null;return i}
function generateTemplates(k){let mo=budget.monthlyData[k]||{income:[],expenses:[],savings:{amount:0,paid:false,date:''},meta:{}};let changed=false;(budget.recurringTemplates||[]).forEach(t=>{let occ=occurrence(t,k);if(occ==null)return;let list=t.kind==='income'?mo.income:mo.expenses;if(list.some(r=>r.templateId===t.id))return;let day=Math.min(num(t.dueDay)||1,new Date(+k.slice(0,4),+k.slice(5,7),0).getDate());list.push({name:t.name,amount:num(t.amount),cat:t.cat||'autres',paid:false,paidDate:'',dueDate:t.kind==='income'?'':`${k}-${p2(day)}`,templateId:t.id,recurring:true,auto:!!t.auto,createdPeriod:k});changed=true});budget.monthlyData[k]=mo;if(changed)saveBudget()}
function totals(m=monthObj()){let tin=0,tex=0,pin=0,pex=0;(m.income||[]).forEach(r=>{tin+=num(r.amount);if(r.paid||r.auto||/salaire|paie/i.test(r.name||''))pin+=num(r.amount)});(m.expenses||[]).forEach(r=>{tex+=num(r.amount);if(r.paid)pex+=num(r.amount)});let sav=num(m.savings?.amount);return {tin,tex,pin,pex,sav,remaining:pin-tex,current:pin-pex,future:tex-pex,pct:tin?Math.round(tex/tin*100):0}}
function catTotals(m=monthObj()){let o={};(m.expenses||[]).forEach(r=>o[r.cat||'autres']=(o[r.cat||'autres']||0)+num(r.amount));return o}
function dateLabel(s){if(!s)return 'Sans date';let d=new Date(s+'T12:00:00');return d.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}
function daysUntil(s){if(!s)return null;let a=new Date();a.setHours(0,0,0,0);let b=new Date(s+'T00:00:00');return Math.ceil((b-a)/86400000)}
function birthdayNext(b){if(!b.birthDate)return null;let d=new Date(b.birthDate+'T12:00:00'),n=new Date(),y=n.getFullYear();let next=new Date(y,d.getMonth(),d.getDate());next.setHours(0,0,0,0);let t=new Date();t.setHours(0,0,0,0);if(next<t)next=new Date(y+1,d.getMonth(),d.getDate());let age=next.getFullYear()-d.getFullYear();return {date:iso(next.getFullYear(),next.getMonth(),next.getDate()),days:Math.ceil((next-t)/86400000),age}}
function installmentItems(){return (budget.recurringTemplates||[]).filter(t=>t.kind==='expense'&&num(t.installments)>0).map(t=>{let sk=(t.startDate||'').slice(0,7),elapsed=Math.max(0,monthsBetween(sk,key())),paid=Math.min(num(t.installments),elapsed+1);return {...t,paidCount:paid,remainingCount:Math.max(0,num(t.installments)-paid),remainingAmount:Math.max(0,num(t.installments)-paid)*num(t.amount)}}).filter(x=>x.remainingCount>0)}
function annualItems(){let map=new Map();(budget.recurringTemplates||[]).filter(t=>t.kind==='expense'&&num(t.installments)===0&&t.freq!=='once').forEach(t=>map.set(t.id,{name:t.name,monthly:num(t.amount),annual:num(t.amount)*12,cat:t.cat||'autres'}));if(!map.size){(monthObj().expenses||[]).filter(r=>r.recurring||r.templateId).forEach(r=>map.set(r.templateId||r.name,{name:r.name,monthly:num(r.amount),annual:num(r.amount)*12,cat:r.cat||'autres'}))}return [...map.values()].sort((a,b)=>b.annual-a.annual)}
function upcomingExpenses(){return (monthObj().expenses||[]).filter(r=>!r.paid&&r.dueDate).slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate))}
function setTitle(t,showPeriod=true){$('#title').textContent=t;$('#periodBtn').style.display=showPeriod?'':'none';$('#periodBtn').textContent=`${ML[month]} ${year}⌄`}
function navActive(){ $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page)) }
function render(){monthObj();navActive();let fn={home:renderHome,transactions:renderTransactions,planning:renderPlanning,analysis:renderAnalysis,savings:renderSavings,plus:renderPlus,birthdays:renderBirthdays,installments:renderInstallments,annual:renderAnnual,exchanges:renderExchanges}[page]||renderHome;fn();updateBadge()}
function updateBadge(){let c=upcomingExpenses().filter(r=>{let d=daysUntil(r.dueDate);return d!=null&&d>=0&&d<=7}).length;$('#bellBadge').hidden=!c;$('#bellBadge').textContent=c}
function rowTx(r,type,idx){return `<div class="row clickable" data-edit-tx="${type}" data-index="${idx}"><div class="ico">${type==='income'?'💰':r.cat==='transport'?'⛽':r.cat==='alimentation'?'🛒':'▣'}</div><div class="row-main"><b>${esc(r.name||'Sans libellé')}</b><small>${type==='income'?'Revenu':CATS[r.cat]||'Autres'}${r.dueDate?' · '+dateLabel(r.dueDate):''}</small></div><div class="amt ${type==='income'?'pos':'neg'}">${type==='income'?'+':'-'}${eur(r.amount)}</div></div>`}
function renderHome(){setTitle('Budget Mensuel+');let t=totals(), bds=extra.birthdays.map(b=>({b,n:birthdayNext(b)})).filter(x=>x.n&&x.n.days<=45).sort((a,b)=>a.n.days-b.n.days);let up=upcomingExpenses().slice(0,3);let goal=goals[0];let gp=goal&&num(goal.target)?Math.min(100,Math.round(num(goal.current)/num(goal.target)*100)):0;let pct=Math.max(0,Math.min(100,t.pct));$('#view').innerHTML=`<div class="stack"><section class="hero"><div class="ring" style="--pct:${pct}%"><b>${pct}%</b></div><div class="label">Reste à dépenser</div><strong>${eur(Math.max(0,t.remaining))}</strong><small>sur ${eur(t.tin)}</small><div class="progress"><span style="width:${Math.max(0,100-pct)}%"></span></div><div class="hero-sub"><span>Dépensé : ${eur(t.tex)}</span><span>Budget : ${eur(t.tin)}</span></div></section>${bds.length?`<div><div class="sec-head"><h2>Prévisions & Anticipations</h2><button class="link" data-go="planning">Voir tout ›</button></div><section class="card anticip" data-go="birthdays"><div class="big">🎂 Anniversaires</div><div class="meta">À venir · ${esc(bds[0].b.name)}</div><div class="days">${bds[0].n.days===0?'Aujourd’hui':bds[0].n.days+' jours restants'}</div><div class="meta">Âge : ${bds[0].n.age} ans · Budget ${eur(bds[0].b.budget)}</div></section></div>`:''}<div><div class="sec-head"><h2>À venir cette semaine</h2></div><section class="card upcoming">${up.length?up.map((r,i)=>rowTx(r,'expense',monthObj().expenses.indexOf(r))).join(''):'<div class="empty">Aucune dépense prévue cette semaine.</div>'}</section></div>${goal?`<section class="hero" style="padding:14px"><div class="label">Mon objectif épargne</div><strong style="font-size:18px">${eur(goal.current)} <small>/ ${eur(goal.target)}</small></strong><div class="progress"><span style="width:${gp}%"></span></div><div class="hero-sub"><span>${esc(goal.n)}</span><span>${gp}%</span></div></section>`:''}</div>`}
function renderTransactions(){setTitle('Transactions');let m=monthObj(),rows=[];(m.income||[]).forEach((r,i)=>rows.push({r,t:'income',i}));(m.expenses||[]).forEach((r,i)=>rows.push({r,t:'expense',i}));if(txFilter!=='all')rows=rows.filter(x=>x.t===txFilter);$('#view').innerHTML=`<div class="stack"><div class="monthbar"><select id="mSel">${ML.map((x,i)=>`<option value="${i}" ${i===month?'selected':''}>${x}</option>`).join('')}</select><select id="ySel">${[year-1,year,year+1].map(y=>`<option ${y===year?'selected':''}>${y}</option>`).join('')}</select></div><div class="summary"><div><small>Solde du mois</small></div><strong>${tSign(totals().remaining)}</strong></div><div class="tabs"><button data-filter="all" class="${txFilter==='all'?'active':''}">Toutes</button><button data-filter="income" class="${txFilter==='income'?'active':''}">Revenus</button><button data-filter="expense" class="${txFilter==='expense'?'active':''}">Dépenses</button></div><section class="card list">${rows.length?rows.map(x=>rowTx(x.r,x.t,x.i)).join(''):'<div class="empty">Aucune transaction.</div>'}</section><button class="action tx-add" data-add-tx>＋ Ajouter une transaction</button></div>`}
function tSign(v){return (v>=0?'+':'')+eur(v)}
function eventsForDay(d){let ds=iso(year,month,d),a=[];(monthObj().income||[]).forEach(r=>{if(r.dueDate===ds||(!r.dueDate&&d===1))a.push('green')});(monthObj().expenses||[]).forEach(r=>{if(r.dueDate===ds){let t=r.templateId&&(budget.recurringTemplates||[]).find(x=>x.id===r.templateId);a.push(t&&num(t.installments)>0?'orange':'red')}});extra.birthdays.forEach(b=>{let n=birthdayNext(b);if(n&&n.date===ds)a.push('pink')});return [...new Set(a)].slice(0,3)}
function renderPlanning(){setTitle('Planification');let first=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),todayD=new Date(),cells='';for(let i=0;i<first;i++)cells+='<span></span>';for(let d=1;d<=days;d++){let ev=eventsForDay(d),is=todayD.getFullYear()===year&&todayD.getMonth()===month&&todayD.getDate()===d;cells+=`<div class="day ${is?'today':''}"><b>${d}</b><div class="dots">${ev.map(c=>`<i class="dot d-${c}"></i>`).join('')}</div></div>`}let evs=upcomingExpenses().slice(0,4);let nextBd=extra.birthdays.map(b=>({b,n:birthdayNext(b)})).filter(x=>x.n&&x.n.days<=45).sort((a,b)=>a.n.days-b.n.days)[0];$('#view').innerHTML=`<div class="stack"><div class="tabs"><button class="active">Calendrier</button><button>Agenda</button><button data-open-birthday>＋</button></div><section class="card calendar"><div class="cal-head"><button data-shift="-1">‹</button><b>${ML[month]} ${year}</b><button data-shift="1">›</button></div><div class="week">${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=>`<span>${x}</span>`).join('')}</div><div class="grid">${cells}</div><div class="legend"><span><i class="d-green"></i>Revenus</span><span><i class="d-red"></i>Dépenses fixes</span><span><i class="d-orange"></i>Échéances</span><span><i class="d-pink"></i>Anniversaires</span></div></section><div><div class="sec-head"><h2>Prochains événements</h2></div><section class="card list">${nextBd?`<div class="row clickable" data-go="birthdays"><div class="ico">🎂</div><div class="row-main"><b>${esc(nextBd.b.name)} — Anniversaire</b><small>${dateLabel(nextBd.n.date)} · ${nextBd.n.days} jours</small></div></div>`:''}${evs.map(r=>rowTx(r,'expense',monthObj().expenses.indexOf(r))).join('')||(!nextBd?'<div class="empty">Aucun événement à venir.</div>':'')}</section></div></div>`}
function renderAnalysis(){setTitle('Analyses');let t=totals(),ct=catTotals(),keys=Object.keys(ct).sort((a,b)=>ct[b]-ct[a]),total=t.tex||1,conic=[],acc=0;keys.forEach(k=>{let p=ct[k]/total*100;conic.push(`${COLORS[k]||'#999'} ${acc}% ${acc+p}%`);acc+=p});let annual=annualItems(),annualTotal=annual.reduce((s,x)=>s+x.annual,0),inst=installmentItems(),instRemain=inst.reduce((s,x)=>s+x.remainingAmount,0);let prevK=month===0?`${year-1}-12`:`${year}-${p2(month)}`,prev=budget.monthlyData[prevK]?totals(budget.monthlyData[prevK]):{tex:0},diff=prev.tex?Math.round((t.tex-prev.tex)/prev.tex*100):0;let monthly=[];for(let i=0;i<12;i++){let m=budget.monthlyData[`${year}-${p2(i+1)}`];monthly.push(m?totals(m).tex:0)}let mx=Math.max(1,...monthly);let saveRate=t.tin?Math.round(t.sav/t.tin*100):0;let fixed=(monthObj().expenses||[]).filter(r=>r.recurring||r.templateId).reduce((s,r)=>s+num(r.amount),0);let fixedRate=t.tin?Math.round(fixed/t.tin*100):0;$('#view').innerHTML=`<div class="stack"><section class="card"><div class="sec-head"><h2>Répartition des dépenses</h2></div><div class="donut-wrap"><div class="donut" style="background:conic-gradient(${conic.join(',')||'#e9efeb 0 100%'})"><div class="donut-center"><div><b>${eur(t.tex)}</b><br>Total</div></div></div><div class="legend-list">${keys.slice(0,6).map(k=>`<div class="leg"><i style="background:${COLORS[k]}"></i><span>${CATS[k]||k}</span><b>${Math.round(ct[k]/total*100)}%</b></div>`).join('')}</div></div></section><section class="card"><div class="sec-head"><h2>Évolution des dépenses</h2><b class="${diff>0?'neg':'pos'}">${diff>0?'+':''}${diff}%</b></div><div class="chart">${monthly.map((v,i)=>`<div class="bar ${i===month?'active':''}" style="height:${Math.max(3,v/mx*100)}%" title="${ML[i]} ${eur(v)}"></div>`).join('')}</div></section><div class="metric-grid"><div class="metric"><small>Taux d’épargne</small><b class="pos">${saveRate}%</b></div><div class="metric"><small>Charges fixes / revenus</small><b>${fixedRate}%</b></div><div class="metric annual-box" data-go="annual"><small>Coût annuel récurrent</small><b class="blue">${eur(annualTotal)}</b></div><div class="metric install-box" data-go="installments"><small>Échéanciers restants</small><b style="color:var(--orange)">${eur(instRemain)}</b></div></div><section class="card"><div class="sec-head"><h2>Top 5 des dépenses</h2></div>${(monthObj().expenses||[]).slice().sort((a,b)=>num(b.amount)-num(a.amount)).slice(0,5).map(r=>`<div class="row"><div class="row-main"><b>${esc(r.name)}</b><small>${CATS[r.cat]||'Autres'}</small></div><b>${eur(r.amount)}</b></div>`).join('')}</section><div class="insight"><b>Analyse intelligente</b><br>${fixedRate>60?'Tes charges fixes dépassent 60 % de tes revenus : garde une marge pour les dépenses variables.':saveRate>=15?'Ton taux d’épargne est solide ce mois-ci.':'Une épargne régulière, même petite, rend tes mois futurs plus prévisibles.'}</div></div>`}
function renderSavings(){setTitle('Épargne');let t=totals(),rate=t.tin?Math.round(t.sav/t.tin*100):0,total=goals.reduce((s,g)=>s+num(g.current),0),target=goals.reduce((s,g)=>s+num(g.target),0);$('#view').innerHTML=`<div class="stack"><section class="card savings-hero"><div><small>Épargne ce mois-ci</small><h2 class="pos" style="margin:6px 0">${eur(t.sav)}</h2><small>${rate}% du revenu</small></div><div class="pig">🐷</div></section><div><div class="sec-head"><h2>Objectifs d’épargne</h2><button class="link" data-add-goal>＋</button></div><section class="card">${goals.length?goals.map((g,i)=>{let p=num(g.target)?Math.min(100,Math.round(num(g.current)/num(g.target)*100)):0;return `<div class="goal clickable" data-edit-goal="${i}"><div class="goal-top"><b>${g.e||'🎯'} ${esc(g.n)}</b><b>${p}%</b></div><small>${eur(g.current)} / ${eur(g.target)}</small><div class="progress"><span style="width:${p}%"></span></div></div>`}).join(''):'<div class="empty">Aucun objectif d’épargne.</div>'}</section></div><section class="detail-total mint"><small>Total épargné</small><h2 style="margin:4px 0">${eur(total)}</h2><small>${target?Math.round(total/target*100):0}% des objectifs cumulés</small></section></div>`}
function menuRow(ic,title,sub,action){return `<div class="row clickable" ${action||''}><div class="ico">${ic}</div><div class="row-main"><b>${title}</b>${sub?`<small>${sub}</small>`:''}</div><span class="chev">›</span></div>`}
function renderPlus(){setTitle('Plus',false);$('#view').innerHTML=`<div class="stack"><section class="card menu-profile"><div class="avatar">●</div><div><b>Mon Budget</b><br><small style="color:var(--mut)">Gérez votre budget facilement</small></div></section><div><div class="group-title">Gestion</div><section class="card menu">${menuRow('▣','Comptes & Budget','', 'data-open-budget')}${menuRow('▦','Catégories','', 'data-open-cats')}${menuRow('▰','Moyens de paiement','', 'data-info="Moyens de paiement"')}${menuRow('⚑','Labels','', 'data-info="Labels"')}${menuRow('↻','Règles de récurrence','', 'data-open-recurring')}</section></div><div><div class="group-title">Outils</div><section class="card menu">${menuRow('⇩','Sauvegarde & Export','', 'data-export')}${menuRow('⇧','Importation','', 'data-import')}</section></div><div><div class="group-title">Anticipation</div><section class="card menu">${menuRow('🎂','Anniversaires',`${extra.birthdays.length} enregistré(s)`,'data-go="birthdays"')}${menuRow('💳','Paiements en plusieurs fois',`${installmentItems().length} en cours`,'data-go="installments"')}${menuRow('🗓','Dépenses annuelles','Calculées depuis les dépenses récurrentes','data-go="annual"')}${menuRow('🤝','Échanges / Remboursements',`${extra.exchanges.filter(x=>!x.done).length} en attente`,'data-go="exchanges"')}</section></div></div>`}
function renderBirthdays(){setTitle('Anniversaires',false);let arr=extra.birthdays.map((b,i)=>({b,i,n:birthdayNext(b)})).sort((a,b)=>(a.n?.days??9999)-(b.n?.days??9999));let sum=arr.reduce((s,x)=>s+num(x.b.budget),0);$('#view').innerHTML=`<div class="stack"><div class="sec-head"><button class="link" data-go="plus">‹ Retour</button><button class="link" data-open-birthday>＋</button></div><div class="tabs"><button class="active">À venir</button><button>Tous</button></div><section class="card list">${arr.length?arr.map(x=>`<div class="row clickable" data-edit-birthday="${x.i}"><div class="ico">🎂</div><div class="row-main"><b>${esc(x.b.name)}</b><small>${x.b.birthDate?new Date(x.b.birthDate+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}):''} · ${x.n?.age??'—'} ans</small><small style="color:var(--red);display:block">${x.n?.days===0?'Aujourd’hui':(x.n?.days??'—')+' jours restants'}</small></div><b class="neg">${eur(x.b.budget)}</b></div>`).join(''):'<div class="empty">Aucun anniversaire. Appuie sur + pour en ajouter.</div>'}</section><section class="detail-total pink"><small>Total à prévoir</small><h2 style="margin:4px 0">${eur(sum)}</h2></section></div>`}
function renderInstallments(){setTitle('Paiements en plusieurs fois',false);let arr=installmentItems(),sum=arr.reduce((s,x)=>s+x.remainingAmount,0);$('#view').innerHTML=`<div class="stack"><div class="sec-head"><button class="link" data-go="plus">‹ Retour</button><button class="link" data-add-tx-install>＋</button></div><div class="tabs"><button class="active">En cours</button><button>Terminés</button></div><section class="detail-total orange"><small>Total restant dû</small><h2 style="margin:4px 0">${eur(sum)}</h2><small>${arr.reduce((s,x)=>s+x.remainingCount,0)} échéances à venir</small></section><section class="card list">${arr.length?arr.map(x=>`<div class="row"><div class="ico">▣</div><div class="row-main"><b>${esc(x.name)}</b><small>${eur(x.amount)} / mois · Restant : ${x.paidCount} / ${x.installments}</small></div><b class="neg">-${eur(x.amount)}</b></div>`).join(''):'<div class="empty">Aucun paiement fractionné. Crée-le depuis une dépense avec « Échéancier ».</div>'}</section></div>`}
function renderAnnual(){setTitle('Dépenses annuelles',false);let arr=annualItems(),sum=arr.reduce((s,x)=>s+x.annual,0);$('#view').innerHTML=`<div class="stack"><div class="sec-head"><button class="link" data-go="analysis">‹ Analyses</button></div><section class="card"><div class="insight">Ces montants sont calculés automatiquement depuis tes dépenses récurrentes. Rien à saisir deux fois.</div></section><section class="card list">${arr.length?arr.map(x=>`<div class="row"><div class="ico">🗓</div><div class="row-main"><b>${esc(x.name)}</b><small>${eur(x.monthly)} / mois</small></div><b style="color:var(--blue)">${eur(x.annual)} / an</b></div>`).join(''):'<div class="empty">Aucune dépense récurrente détectée.</div>'}</section><section class="detail-total blue"><small>Total annuel récurrent</small><h2 style="margin:4px 0">${eur(sum)}</h2><small>soit ${eur(sum/12)} / mois en moyenne</small></section></div>`}
function renderExchanges(){setTitle('Échanges / Remboursements',false);let arr=extra.exchanges,sum=arr.filter(x=>!x.done).reduce((s,x)=>s+num(x.amount),0);$('#view').innerHTML=`<div class="stack"><div class="sec-head"><button class="link" data-go="plus">‹ Retour</button><button class="link" data-open-exchange>＋</button></div><div class="tabs"><button class="active">En attente</button><button>Historique</button></div><section class="card list">${arr.length?arr.map((x,i)=>`<div class="row clickable" data-edit-exchange="${i}"><div class="ico">🤝</div><div class="row-main"><b>${esc(x.name)}</b><small>${esc(x.note||'')} ${x.done?'· Remboursé':''}</small></div><b class="${num(x.amount)>=0?'pos':'neg'}">${eur(x.amount)}</b></div>`).join(''):'<div class="empty">Aucun échange enregistré.</div>'}</section><section class="detail-total mint"><small>Total en attente</small><h2 style="margin:4px 0">${eur(sum)}</h2></section></div>`}
function openSheet(title,html){$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;$('#overlay').classList.add('open');$('#sheet').classList.add('open')}
function closeSheet(){$('#overlay').classList.remove('open');$('#sheet').classList.remove('open')}
function txForm(type='expense',idx='',install=false){let r=idx===''?{}:monthObj()[type==='income'?'income':'expenses'][+idx]||{},tpl=r.templateId?(budget.recurringTemplates||[]).find(t=>t.id===r.templateId):null,recur=install?'installments':tpl?.installments?'installments':tpl?.freq==='monthly'?'monthly':'once';openSheet(idx===''?'Ajouter une transaction':'Modifier la transaction',`<form class="form" id="txForm"><input type="hidden" name="type" value="${type}"><input type="hidden" name="idx" value="${idx}"><label>Type<select name="kind"><option value="expense" ${type==='expense'?'selected':''}>Dépense</option><option value="income" ${type==='income'?'selected':''}>Revenu</option></select></label><label>Libellé<input name="name" required value="${esc(r.name||'')}"></label><div class="two"><label>Montant (€)<input type="number" step="0.01" name="amount" required value="${num(r.amount)||''}"></label><label>Date prévue<input type="date" name="date" value="${r.dueDate||today()}"></label></div><label>Catégorie<select name="cat">${Object.keys(CATS).map(k=>`<option value="${k}" ${r.cat===k?'selected':''}>${CATS[k]}</option>`).join('')}</select></label><label>Récurrence<select name="recur"><option value="once" ${recur==='once'?'selected':''}>Ponctuelle</option><option value="monthly" ${recur==='monthly'?'selected':''}>Chaque mois</option><option value="installments" ${recur==='installments'?'selected':''}>Échéancier (paiement en plusieurs fois)</option></select></label><label>Nombre de paiements<input type="number" min="2" name="count" value="${tpl?.installments||''}" placeholder="Ex : 4"></label><label><input type="checkbox" name="paid" ${r.paid?'checked':''}> Déjà payé / reçu</label><button class="action">Enregistrer</button>${idx!==''?'<button type="button" class="ghost danger" data-delete-tx>Supprimer</button>':''}</form>`)}
function birthdayForm(i=''){let b=i===''?{}:extra.birthdays[+i]||{};openSheet(i===''?'Ajouter un anniversaire':'Modifier l’anniversaire',`<form class="form" id="birthdayForm"><input type="hidden" name="idx" value="${i}"><label>Prénom / nom<input name="name" required value="${esc(b.name||'')}"></label><label>Date de naissance<input type="date" name="birthDate" required value="${b.birthDate||''}"></label><label>Budget cadeau prévu (€)<input type="number" step="0.01" name="budget" value="${num(b.budget)||''}"></label><label>Rappel<select name="reminder"><option value="7">7 jours avant</option><option value="14" ${b.reminder==14?'selected':''}>14 jours avant</option><option value="30" ${b.reminder==30?'selected':''}>30 jours avant</option></select></label><label>Note<textarea name="note" rows="2">${esc(b.note||'')}</textarea></label><button class="action">Enregistrer</button>${i!==''?'<button type="button" class="ghost danger" data-delete-birthday>Supprimer</button>':''}</form>`)}
function goalForm(i=''){let g=i===''?{}:goals[+i]||{};openSheet(i===''?'Nouvel objectif':'Modifier l’objectif',`<form class="form" id="goalForm"><input type="hidden" name="idx" value="${i}"><label>Nom<input name="name" required value="${esc(g.n||'')}"></label><label>Icône<input name="emoji" value="${esc(g.e||'🎯')}"></label><div class="two"><label>Objectif (€)<input type="number" name="target" step="1" value="${num(g.target)||''}"></label><label>Déjà épargné (€)<input type="number" name="current" step="1" value="${num(g.current)||''}"></label></div><button class="action">Enregistrer</button>${i!==''?'<button type="button" class="ghost danger" data-delete-goal>Supprimer</button>':''}</form>`)}
function exchangeForm(i=''){let x=i===''?{}:extra.exchanges[+i]||{};openSheet(i===''?'Nouvel échange':'Modifier l’échange',`<form class="form" id="exchangeForm"><input type="hidden" name="idx" value="${i}"><label>Personne / motif<input name="name" required value="${esc(x.name||'')}"></label><label>Montant (€)<input type="number" step="0.01" name="amount" value="${num(x.amount)||''}"><small>Positif = on me doit, négatif = je dois.</small></label><label>Note<input name="note" value="${esc(x.note||'')}"></label><label><input type="checkbox" name="done" ${x.done?'checked':''}> Remboursé / terminé</label><button class="action">Enregistrer</button>${i!==''?'<button type="button" class="ghost danger" data-delete-exchange>Supprimer</button>':''}</form>`)}
function saveTx(fd){let type=fd.get('kind'),idx=fd.get('idx'),name=fd.get('name').trim(),amount=num(fd.get('amount')),date=fd.get('date'),cat=fd.get('cat'),paid=fd.get('paid')==='on',recur=fd.get('recur'),count=Math.max(0,Math.round(num(fd.get('count'))));let mo=monthObj(),list=type==='income'?mo.income:mo.expenses,old=idx!==''?list[+idx]:null;let row=old||{};Object.assign(row,{name,amount,cat,paid,paidDate:paid?today():'',dueDate:type==='income'?'':date});if(idx==='')list.push(row);
 if(recur!=='once'){let tpl=old?.templateId?(budget.recurringTemplates||[]).find(t=>t.id===old.templateId):null;if(!tpl){tpl={id:'tpl_'+Date.now()+Math.random().toString(36).slice(2,6)};budget.recurringTemplates.push(tpl)}Object.assign(tpl,{kind:type,name,amount,cat,freq:'monthly',interval:1,installments:recur==='installments'?Math.max(2,count||2):0,startDate:tpl.startDate||date||`${key()}-01`,dueDay:date?+date.slice(-2):1,auto:false});row.templateId=tpl.id;row.recurring=true}else if(row.templateId){let ti=budget.recurringTemplates.findIndex(t=>t.id===row.templateId);if(ti>=0)budget.recurringTemplates.splice(ti,1);delete row.templateId;delete row.recurring}saveBudget();closeSheet();render()}
function exportData(){let blob=new Blob([JSON.stringify({budget,goals,extra,exported:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`budget-mensuel-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(){openSheet('Importer une sauvegarde',`<form class="form" id="importForm"><label>Fichier JSON<input type="file" name="file" accept="application/json"></label><div class="insight">L’import crée d’abord une sauvegarde de sécurité de tes données actuelles.</div><button class="action">Importer</button></form>`)}
function info(msg){openSheet(msg,`<div class="empty">Cette rubrique conserve le visuel de la maquette. Elle sera alimentée par les données du budget sans modifier les informations existantes.</div>`)}
$('#nav').addEventListener('click',e=>{let b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;render()});
document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g){page=g.dataset.go;render();return}if(e.target.closest('[data-add-tx]'))return txForm();if(e.target.closest('[data-add-tx-install]'))return txForm('expense','',true);if(e.target.closest('[data-open-birthday]'))return birthdayForm();if(e.target.closest('[data-add-goal]'))return goalForm();if(e.target.closest('[data-open-exchange]'))return exchangeForm();let et=e.target.closest('[data-edit-tx]');if(et)return txForm(et.dataset.editTx,et.dataset.index);let eb=e.target.closest('[data-edit-birthday]');if(eb)return birthdayForm(eb.dataset.editBirthday);let eg=e.target.closest('[data-edit-goal]');if(eg)return goalForm(eg.dataset.editGoal);let ex=e.target.closest('[data-edit-exchange]');if(ex)return exchangeForm(ex.dataset.editExchange);let f=e.target.closest('[data-filter]');if(f){txFilter=f.dataset.filter;render();return}let sh=e.target.closest('[data-shift]');if(sh){month+=+sh.dataset.shift;if(month<0){month=11;year--}if(month>11){month=0;year++}saveBudget();render();return}if(e.target.closest('[data-export]'))return exportData();if(e.target.closest('[data-import]'))return importData();if(e.target.closest('[data-open-recurring]')){let a=(budget.recurringTemplates||[]);openSheet('Règles de récurrence',`<section class="card list">${a.length?a.map(t=>`<div class="row"><div class="row-main"><b>${esc(t.name)}</b><small>${t.installments?`Échéancier ${t.installments} paiements`:'Récurrent mensuel'}</small></div><b>${eur(t.amount)}</b></div>`).join(''):'<div class="empty">Aucune règle.</div>'}</section>`);return}let inf=e.target.closest('[data-info]');if(inf)return info(inf.dataset.info);if(e.target.closest('[data-open-budget]'))return info('Comptes & Budget');if(e.target.closest('[data-open-cats]'))return info('Catégories')});
$('#periodBtn').addEventListener('click',()=>openSheet('Choisir la période',`<form class="form" id="periodForm"><label>Mois<select name="month">${ML.map((x,i)=>`<option value="${i}" ${i===month?'selected':''}>${x}</option>`).join('')}</select></label><label>Année<input name="year" type="number" value="${year}"></label><button class="action">Afficher</button></form>`));$('#sheetClose').onclick=closeSheet;$('#overlay').onclick=closeSheet;
document.addEventListener('submit',async e=>{e.preventDefault();let fd=new FormData(e.target);if(e.target.id==='txForm')return saveTx(fd);if(e.target.id==='birthdayForm'){let i=fd.get('idx'),o={name:fd.get('name').trim(),birthDate:fd.get('birthDate'),budget:num(fd.get('budget')),reminder:num(fd.get('reminder')),note:fd.get('note')};i===''?extra.birthdays.push(o):extra.birthdays[+i]=o;saveExtra();closeSheet();render();return}if(e.target.id==='goalForm'){let i=fd.get('idx'),o={id:i===''?'g_'+Date.now():goals[+i]?.id,n:fd.get('name').trim(),e:fd.get('emoji')||'🎯',target:num(fd.get('target')),current:num(fd.get('current'))};i===''?goals.push(o):goals[+i]=o;saveGoals();closeSheet();render();return}if(e.target.id==='exchangeForm'){let i=fd.get('idx'),o={name:fd.get('name').trim(),amount:num(fd.get('amount')),note:fd.get('note'),done:fd.get('done')==='on'};i===''?extra.exchanges.push(o):extra.exchanges[+i]=o;saveExtra();closeSheet();render();return}if(e.target.id==='periodForm'){month=+fd.get('month');year=+fd.get('year');saveBudget();closeSheet();render();return}if(e.target.id==='importForm'){let f=fd.get('file');if(!f||!f.size)return;backup();let obj=safeParse(await f.text(),null);if(!obj)return alert('Fichier invalide');if(obj.budget)budget=obj.budget;if(obj.goals)goals=obj.goals;if(obj.extra)extra=obj.extra;saveBudget();saveGoals();saveExtra();closeSheet();render();alert('Import terminé.');return}});
document.addEventListener('click',e=>{if(e.target.closest('[data-delete-tx]')){let form=$('#txForm'),fd=new FormData(form),type=fd.get('kind'),idx=+fd.get('idx');if(confirm('Supprimer cette transaction ?')){monthObj()[type==='income'?'income':'expenses'].splice(idx,1);saveBudget();closeSheet();render()}return}if(e.target.closest('[data-delete-birthday]')){let i=+new FormData($('#birthdayForm')).get('idx');if(confirm('Supprimer cet anniversaire ?')){extra.birthdays.splice(i,1);saveExtra();closeSheet();render()}return}if(e.target.closest('[data-delete-goal]')){let i=+new FormData($('#goalForm')).get('idx');if(confirm('Supprimer cet objectif ?')){goals.splice(i,1);saveGoals();closeSheet();render()}return}if(e.target.closest('[data-delete-exchange]')){let i=+new FormData($('#exchangeForm')).get('idx');if(confirm('Supprimer cet échange ?')){extra.exchanges.splice(i,1);saveExtra();closeSheet();render()}return}});
document.addEventListener('change',e=>{if(e.target.id==='mSel'){month=+e.target.value;saveBudget();render()}if(e.target.id==='ySel'){year=+e.target.value;saveBudget();render()}});
window.addEventListener('error',e=>console.error('Budget Mensuel+',e.error||e.message));render();
})();
