(function(){
'use strict';
const ML=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const cats={logement:['Logement','🏠'],transport:['Transport','🚗'],alimentation:['Alimentation','🛒'],abonnements:['Abonnements','📱'],enfants:['Enfants','👶'],credits:['Crédits','💳'],assurances:['Assurances','🛡️'],loisirs:['Loisirs','🎬'],sante:['Santé','💊'],autres:['Autres','📦']};
const goals=[{n:'Maison',e:'🏡',target:80000},{n:'Voyage',e:'✈️',target:3000},{n:'Voiture',e:'🚗',target:10000}];
let month=new Date().getMonth();let app=load();let currentPage='dashboard';
function $(id){return document.getElementById(id)};function eur(v){v=Number(v)||0;return v.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}function short(v){v=Number(v)||0;return Math.abs(v)>=1000?(v/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})+'k €':eur(v)}function p2(n){return String(n).padStart(2,'0')}function dateFR(s){if(!s)return'Sans date';let p=s.split('-');return p[2]+'/'+p[1]}function today(){let d=new Date();return d.getFullYear()+'-'+p2(d.getMonth()+1)+'-'+p2(d.getDate())}
function mkRow(n,a,d,c){return{name:n||'',amount:Number(a)||0,paid:false,dueDate:d||'',paidDate:'',cat:c||'autres'}}function isAutoIncome(r){return !!(r&&r.auto)||/salaire|paie|pay/i.test(r?.name||'')}function defIncome(){let sal=mkRow('Salaire',0,'','autres');sal.auto=true;sal.paid=true;return[sal,mkRow('Revenus supplémentaires',0,'','autres')]}function defExpenses(){return[mkRow('Logement',0,'','logement'),mkRow('Supermarché',0,'','alimentation'),mkRow('Assurance voiture',0,'','assurances'),mkRow('Essence',0,'','transport'),mkRow('Free mobile',0,'','abonnements')]}function defMonth(){return{income:defIncome(),expenses:defExpenses(),savings:{amount:0,paid:false,date:''}}}
function fix(r){r.amount=Number(r.amount)||0;r.paid=!!r.paid;r.dueDate=r.dueDate||'';r.paidDate=r.paidDate||'';r.cat=r.cat||'autres';if(isAutoIncome(r)){r.auto=true;r.paid=true}}
function normalize(d){if(!d)d={currentMonth:new Date().getMonth(),months:{}};if(!d.months)d.months={};for(let i=0;i<12;i++){let m=d.months[i]||d.months[String(i)]||defMonth();m.income=m.income||defIncome();m.expenses=m.expenses||defExpenses();m.savings=m.savings||{amount:0,paid:false,date:''};m.income.forEach(fix);m.expenses.forEach(fix);m.savings.amount=Number(m.savings.amount)||0;m.savings.paid=!!m.savings.paid;d.months[i]=m}if(!d.savings)d.savings={balance:0,target:50000,monthlyTarget:1000,history:{}};if(!d.savings.history)d.savings.history={};return d}
function load(){let keys=['bgt4','budgetV3','budgetV2'];for(let k of keys){try{let v=localStorage.getItem(k);if(v)return normalize(JSON.parse(v))}catch(e){}}let d=normalize(null);d.months[month].income[0].amount=1500;d.months[month].expenses=[mkRow('Prêt lit',289,`2026-${p2(month+1)}-02`,'logement'),mkRow('Supermarché',170,'','alimentation'),mkRow('Assurance voiture',100,`2026-${p2(month+1)}-05`,'assurances'),mkRow('Essence',100,`2026-${p2(month+1)}-15`,'transport'),mkRow('Free mobile',38,`2026-${p2(month+1)}-25`,'abonnements'),mkRow('Autres',300,`2026-${p2(month)}-30`,'autres')];return d}
function save(){try{localStorage.setItem('bgt4',JSON.stringify(app))}catch(e){}}
function m(){return app.months[month]}function totals(){let mi=m(),tin=0,tex=0,pin=0,pex=0;mi.income.forEach(r=>{tin+=r.amount;if(r.paid||isAutoIncome(r))pin+=r.amount});mi.expenses.forEach(r=>{tex+=r.amount;if(r.paid)pex+=r.amount});let future=mi.expenses.filter(r=>!r.paid).reduce((s,r)=>s+r.amount,0);return{tin,tex,pin,pex,solde:pin-pex,final:pin-tex,future,sav:mi.savings.amount||0,pct:tin?Math.round(tex/tin*100):0}}
function catTotals(){let out={};m().expenses.forEach(r=>out[r.cat]=(out[r.cat]||0)+r.amount);return out}
function upcoming(){return m().expenses.filter(r=>!r.paid&&r.amount>0).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).slice(0,4)}
function spark(){let t=totals(), vals=[t.pin,t.pin-120,t.pin-140,t.pin-200,t.pin-200,t.final];let max=Math.max(...vals),min=Math.min(...vals);let pts=vals.map((v,i)=>`${i*56},${60-((v-min)/(max-min||1))*48}`).join(' ');return `<svg viewBox="0 0 280 70"><polyline points="${pts}" fill="none" stroke="rgba(255,255,255,.35)" stroke-width="13" stroke-linecap="round" stroke-linejoin="round"/><polyline points="${pts}" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function renderDashboard(){let t=totals(), up=upcoming();$('page-dashboard').innerHTML=`<div class="orion-note"><div class="bot">🤖</div><div><b>ORION</b><br>Tu ${t.final>=0?'gardes':'risques de perdre'} ${eur(Math.abs(t.final))} en fin de mois.</div></div><section class="hero"><div class="status-pill">${t.final>=0?'Stable':'Attention'}</div><div class="eyebrow">Disponible</div><div class="hero-amount">${eur(t.solde)}</div><div class="hero-sub">Fin du mois estimée : <b>${eur(t.final)}</b></div><div class="spark">${spark()}</div></section><div class="kpi-grid"><article class="kpi"><div class="ico">↗</div><h3>Revenus</h3><strong>${short(t.tin)}</strong><p>${eur(t.pin)} comptés</p></article><article class="kpi red"><div class="ico">↘</div><h3>Dépenses</h3><strong>${short(t.tex)}</strong><p>${eur(t.pex)} confirmées</p></article><article class="kpi blue"><div class="ico">💰</div><h3>Épargne</h3><strong>${eur(t.sav)}</strong><p>ce mois</p></article><article class="kpi orange"><div class="ico">⚠</div><h3>À payer</h3><strong>${eur(t.future)}</strong><p>prélèvements futurs</p></article></div><section class="card"><h2>Aujourd’hui</h2>${up.map((r,i)=>row(r,'expense',i)).join('')||'<p>Aucun prélèvement à venir.</p>'}</section><section class="card"><h2>Objectifs</h2><div class="goal-grid">${goals.map(g=>goalMini(g)).join('')}</div></section><section class="card"><h2>Conseil ORION</h2><div class="insight"><div class="ico">✨</div><div><b>${t.pct<80?'Budget sous contrôle':'Budget à surveiller'}</b><p>Plus gros poste : ${biggestCat()}.</p></div></div></section>`}
function row(r,type,i){let done=r.paid||isAutoIncome(r);let sign=type==='income'?'+':'-';return `<div class="row ${done?'done':''}" data-toggle="${type}" data-index="${i}"><div class="check">✓</div><div class="row-main"><div class="row-title">${cats[r.cat]?.[1]||''} ${r.name}</div><div class="row-meta">${done?'Confirmé':'Prévu'} · ${dateFR(r.dueDate)}</div></div><div class="amount ${type==='income'?'pos':'neg'}">${sign}${eur(r.amount)}</div></div>`}
function goalMini(g){let cap=Number(app.savings?.balance)||0,p=Math.min(100,Math.round(cap/g.target*100));return `<div class="goal-mini"><div class="emoji">${g.e}</div><b>${g.n}</b><div class="circle" style="--p:${p}%">${p}%</div><small>${eur(cap)} / ${eur(g.target)}</small></div>`}
function biggestCat(){let ct=catTotals(),ks=Object.keys(ct).sort((a,b)=>ct[b]-ct[a]);return ks[0]?(cats[ks[0]]?.[0]||ks[0])+' · '+eur(ct[ks[0]]):'aucune dépense'}
function renderTransactions(){let rows=[...m().income.map((r,i)=>({...r,type:'income',idx:i})),...m().expenses.map((r,i)=>({...r,type:'expense',idx:i}))];$('page-transactions').innerHTML=`<section class="card"><div class="list-head"><h2>Transactions</h2><button class="icon-btn" id="addLine">+</button></div><div class="tabs"><button class="tab active">Tout</button><button class="tab">Revenus</button><button class="tab">Dépenses</button></div>${rows.map(r=>`<div class="tx-row" data-edit="${r.type}" data-index="${r.idx}"><div class="tx-icon">${r.type==='income'?'✅':(cats[r.cat]?.[1]||'💳')}</div><div class="tx-info"><b>${r.name}</b><p>${r.type==='income'?'Revenu':(cats[r.cat]?.[0]||'Autres')} · ${dateFR(r.dueDate)}</p></div><div class="amount ${r.type==='income'?'pos':'neg'}">${r.type==='income'?'+':'-'}${eur(r.amount)}</div></div>`).join('')}</section>`}
function renderStats(){let ct=catTotals(),max=Math.max(...Object.values(ct),1),t=totals();$('page-stats').innerHTML=`<section class="card"><h2>Répartition</h2><div class="bars">${Object.keys(ct).sort((a,b)=>ct[b]-ct[a]).map(k=>`<div class="bar-row"><span>${cats[k]?.[0]||k}</span><div class="bar-bg"><span style="width:${ct[k]/max*100}%"></span></div><b>${eur(ct[k])}</b></div>`).join('')}</div></section><section class="card"><h2>Comparaison</h2><div class="insight"><div class="ico">📈</div><div><b>Ce mois : ${eur(t.final)}</b><p>Dépenses : ${eur(t.tex)} · Revenus : ${eur(t.tin)}</p></div></div></section><section class="card"><h2>Courbe du mois</h2><div class="spark">${spark()}</div></section>`}
function renderGoals(){$('page-goals').innerHTML=goals.map(g=>`<section class="card goal-card"><div class="big-emoji">${g.e}</div><div class="middle"><h3>${g.n}</h3><p>${eur(Number(app.savings?.balance)||0)} / ${eur(g.target)}</p><div class="progress"><span style="width:${Math.min(100,(Number(app.savings?.balance)||0)/g.target*100)}%"></span></div></div><b>${Math.min(100,Math.round((Number(app.savings?.balance)||0)/g.target*100))}%</b></section>`).join('')}
function renderSettings(){$('page-settings').innerHTML=`<section class="card settings-area"><h2>Données</h2><button class="primary" id="exportBtn">Exporter JSON</button><br><br><textarea id="jsonArea" placeholder="Export / import JSON"></textarea><br><br><button class="secondary" id="importBtn">Importer JSON</button></section><section class="card"><h2>Infos</h2><div class="insight"><div class="ico">✅</div><div><b>Compatibilité ancienne app</b><p>Lecture automatique de bgt4, budgetV3 et budgetV2.</p></div></div></section>`}
function render(){ $('monthLabel').textContent=ML[month]+' '+new Date().getFullYear(); renderDashboard(); renderTransactions(); renderStats(); renderGoals(); renderSettings(); }
function switchPage(p){currentPage=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('page-'+p).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'})}
function openSheet(type='expense',idx=''){let r=idx!==''?(type==='income'?m().income[idx]:m().expenses[idx]):mkRow('',0,today(),'autres');$('editType').value=type;$('editIndex').value=idx;$('editName').value=r.name;$('editAmount').value=r.amount||'';$('editDate').value=r.dueDate||today();$('editCat').innerHTML=Object.keys(cats).map(k=>`<option value="${k}" ${r.cat===k?'selected':''}>${cats[k][1]} ${cats[k][0]}</option>`).join('');$('btnDelete').style.display=idx===''?'none':'';$('sheetBackdrop').classList.add('open');$('editorSheet').classList.add('open')}
function closeSheet(){$('sheetBackdrop').classList.remove('open');$('editorSheet').classList.remove('open')}
function saveLine(){let type=$('editType').value,idx=$('editIndex').value;let r=mkRow($('editName').value,$('editAmount').value,$('editDate').value,$('editCat').value);if(type==='income'){r.paid=true;if(idx==='')m().income.push(r);else Object.assign(m().income[idx],r)}else{if(idx==='')m().expenses.push(r);else Object.assign(m().expenses[idx],r)}save();render();closeSheet()}
function delLine(){let type=$('editType').value,idx=$('editIndex').value;if(idx==='')return;if(type==='income')m().income.splice(idx,1);else m().expenses.splice(idx,1);save();render();closeSheet()}
document.addEventListener('click',e=>{let nav=e.target.closest('.bottom-nav button');if(nav)return switchPage(nav.dataset.page);let r=e.target.closest('[data-toggle]');if(r){let arr=r.dataset.toggle==='income'?m().income:m().expenses;let item=arr[r.dataset.index];if(!isAutoIncome(item)){item.paid=!item.paid;item.paidDate=item.paid?today():'';save();render()}return}let ed=e.target.closest('[data-edit]');if(ed)return openSheet(ed.dataset.edit,ed.dataset.index);if(e.target.id==='addLine')return openSheet('expense','');if(e.target.id==='btnCloseSheet'||e.target.id==='sheetBackdrop')return closeSheet();if(e.target.id==='btnSaveLine')return saveLine();if(e.target.id==='btnDelete')return delLine();if(e.target.id==='btnRefresh'){app=load();render();return}if(e.target.id==='exportBtn'){$('jsonArea').value=JSON.stringify(app,null,2);return}if(e.target.id==='importBtn'){try{app=normalize(JSON.parse($('jsonArea').value));save();render();alert('Import OK')}catch(err){alert('JSON invalide')}}});
render();
})();
