(function(){
'use strict';
const ML=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
const cats={logement:['Logement','⌂'],transport:['Transport','↗'],alimentation:['Alimentation','◍'],abonnements:['Abonnements','▥'],enfants:['Enfants','♡'],credits:['Crédits','▤'],assurances:['Assurances','◈'],loisirs:['Loisirs','✦'],sante:['Santé','✚'],autres:['Autres','●']};
const defaultGoals=[{id:'maison',n:'Maison',e:'🏡',target:80000},{id:'urgence',n:"Fonds d'urgence",e:'🛡️',target:10000},{id:'voyage',n:'Voyage',e:'✈️',target:3000}];
let month=new Date().getMonth();let currentPage='dashboard';let filter='all';let app=load();let goals=loadGoals();
function $(id){return document.getElementById(id)}
function eur(v){v=Number(v)||0;return v.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function short(v){v=Number(v)||0;return Math.abs(v)>=1000?(v/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})+'k €':eur(v)}
function p2(n){return String(n).padStart(2,'0')}function today(){let d=new Date();return d.getFullYear()+'-'+p2(d.getMonth()+1)+'-'+p2(d.getDate())}
function dateFR(s){if(!s)return'Sans date';let p=String(s).split('-');return p.length===3?p[2]+'/'+p[1]:'Sans date'}
function mkRow(n,a,d,c){return{name:n||'',amount:Number(a)||0,paid:false,dueDate:d||'',paidDate:'',cat:c||'autres'}}
function isAutoIncome(r){return !!(r&&r.auto)||/salaire|paie|pay/i.test((r&&r.name)||'')}
function guessCat(n){n=(n||'').toLowerCase();if(/loyer|pret|prêt|logement|electricit|électricit|gaz|eau|immo|lit/.test(n))return'logement';if(/voiture|essence|autoroute|vinci|parking|transport/.test(n))return'transport';if(/supermarch|course|aliment|restaurant|carrefour/.test(n))return'alimentation';if(/mobile|internet|freebox|netflix|spotify|apple|abonnement|cap|chat/.test(n))return'abonnements';if(/cantine|ecole|école|creche|crèche|enfant/.test(n))return'enfants';if(/credit|crédit|cetelem|natixis|cofidis|klarna/.test(n))return'credits';if(/assurance|mutuelle/.test(n))return'assurances';if(/loisir|vacance|cinema|cinéma|sport/.test(n))return'loisirs';if(/pharma|medecin|médecin|sante|santé/.test(n))return'sante';return'autres'}
function defIncome(){let sal=mkRow('Salaire',0,'','autres');sal.auto=true;sal.paid=true;let sup=mkRow('Revenus supplémentaires',0,'','autres');sup.auto=false;return[sal,sup]}
function defExpenses(){return[mkRow('Logement',0,'','logement'),mkRow('Supermarché',0,'','alimentation'),mkRow('Assurance voiture',0,'','assurances'),mkRow('Essence',0,'','transport'),mkRow('Free mobile',0,'','abonnements')]}
function defMonth(){return{income:defIncome(),expenses:defExpenses(),savings:{amount:0,paid:false,date:''}}}
function fix(r){r.name=r.name||'';r.amount=Number(r.amount)||0;r.paid=!!r.paid;r.dueDate=r.dueDate||'';r.paidDate=r.paidDate||'';r.cat=r.cat||guessCat(r.name);if(isAutoIncome(r)){r.auto=true;r.paid=true}}
function normalize(d){if(!d)d={currentMonth:new Date().getMonth(),months:{}};if(!d.months)d.months={};for(let i=0;i<12;i++){let m=d.months[i]||d.months[String(i)]||defMonth();m.income=Array.isArray(m.income)?m.income:defIncome();m.expenses=Array.isArray(m.expenses)?m.expenses:defExpenses();m.savings=m.savings||{amount:0,paid:false,date:''};m.income.forEach(fix);m.expenses.forEach(fix);m.savings.amount=Number(m.savings.amount)||0;m.savings.paid=!!m.savings.paid;m.savings.date=m.savings.date||'';d.months[i]=m}if(!d.savings)d.savings={balance:0,target:50000,monthlyTarget:1000,history:{}};if(!d.savings.history)d.savings.history={};month=Number.isInteger(d.currentMonth)?d.currentMonth:new Date().getMonth();return d}
function load(){let keys=['bgt4','budgetV3','budgetV2'];for(let k of keys){try{let v=localStorage.getItem(k);if(v)return normalize(JSON.parse(v))}catch(e){console.warn('Lecture impossible',k,e)}}let d=normalize(null);d.months[month].income[0].amount=1500;d.months[month].expenses=[mkRow('Prêt lit',289,`${new Date().getFullYear()}-${p2(month+1)}-02`,'logement'),mkRow('Supermarché',170,'','alimentation'),mkRow('Assurance voiture',100,`${new Date().getFullYear()}-${p2(month+1)}-05`,'assurances'),mkRow('Essence',100,`${new Date().getFullYear()}-${p2(month+1)}-15`,'transport'),mkRow('Free mobile',38,`${new Date().getFullYear()}-${p2(month+1)}-25`,'abonnements'),mkRow('Autres',300,`${new Date().getFullYear()}-${p2(month+1)}-30`,'autres')];return d}
function save(){app.currentMonth=month;try{localStorage.setItem('bgt4',JSON.stringify(app))}catch(e){alert('Sauvegarde impossible')}}
function loadGoals(){try{return JSON.parse(localStorage.getItem('orion_v21_goals')||'null')||defaultGoals}catch(e){return defaultGoals}}
function saveGoals(){try{localStorage.setItem('orion_v21_goals',JSON.stringify(goals))}catch(e){}}
function m(){return app.months[month]}function cap(){return Number(app.savings&&app.savings.balance)||0}
function totals(){let mi=m(),tin=0,tex=0,pin=0,pex=0;mi.income.forEach(r=>{tin+=r.amount;if(r.paid||isAutoIncome(r))pin+=r.amount});mi.expenses.forEach(r=>{tex+=r.amount;if(r.paid)pex+=r.amount});let future=mi.expenses.filter(r=>!r.paid).reduce((s,r)=>s+r.amount,0);return{tin,tex,pin,pex,solde:pin-pex,final:pin-tex,future,sav:mi.savings.amount||0,pct:tin?Math.round(tex/tin*100):0}}
function prevTotals(){let old=month;month=(old+11)%12;let t=totals();month=old;return t}
function catTotals(){let out={};m().expenses.forEach(r=>{if(r.amount>0)out[r.cat]=(out[r.cat]||0)+r.amount});return out}
function upcoming(n=5){return m().expenses.filter(r=>!r.paid&&r.amount>0).sort((a,b)=>(a.dueDate||'9999-99-99').localeCompare(b.dueDate||'9999-99-99')).slice(0,n)}
function spark(){let t=totals(), vals=[t.pin,t.pin-120,t.pin-140,t.pin-200,t.pin-200,t.final];let max=Math.max(...vals),min=Math.min(...vals);let pts=vals.map((v,i)=>`${i*56},${60-((v-min)/(max-min||1))*48}`).join(' ');return `<svg viewBox="0 0 280 70" aria-hidden="true"><polyline points="${pts}" fill="none" stroke="rgba(255,255,255,.26)" stroke-width="13" stroke-linecap="round" stroke-linejoin="round"/><polyline points="${pts}" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function message(){let t=totals(),prev=prevTotals(),delta=t.final-prev.final;if(t.final<0)return `Attention : fin de mois estimée à ${eur(t.final)}.`;if(t.future>0)return `${upcoming(1)[0]?.name||'Un prélèvement'} arrive bientôt. Reste prévu : ${eur(t.final)}.`;return `Budget sous contrôle. Tu gardes ${eur(t.final)} en fin de mois.`}
function renderDashboard(){let t=totals(),up=upcoming(4);$('page-dashboard').innerHTML=`<div class="orion-note"><div class="bot">🤖</div><div><b>ORION</b><p>${message()}</p></div></div><section class="hero"><div class="status-pill">${t.final>=0?'Stable':'Attention'}</div><div class="eyebrow">Solde actuel</div><div class="hero-amount">${eur(t.solde)}</div><div class="hero-sub">Fin du mois estimée : <b>${eur(t.final)}</b></div><div class="spark">${spark()}</div></section><div class="kpi-grid"><article class="kpi"><div class="ico">↗</div><h3>Revenus</h3><strong>${short(t.tin)}</strong><p>${eur(t.pin)} comptés</p></article><article class="kpi red"><div class="ico">↘</div><h3>Dépenses</h3><strong>${short(t.tex)}</strong><p>${eur(t.pex)} confirmées</p></article><article class="kpi blue"><div class="ico">💰</div><h3>Épargne</h3><strong>${eur(t.sav)}</strong><p>ce mois</p></article><article class="kpi orange"><div class="ico">!</div><h3>À payer</h3><strong>${eur(t.future)}</strong><p>prélèvements futurs</p></article></div><section class="card"><div class="section-head"><h2>Aujourd’hui</h2><button class="tab" data-page-go="transactions">Voir tout</button></div>${up.map((r,i)=>row(r,'expense',m().expenses.indexOf(r))).join('')||'<p class="empty">Aucun prélèvement à venir.</p>'}</section><section class="card"><div class="section-head"><h2>Objectifs</h2><button class="tab" data-page-go="goals">Voir tous</button></div><div class="goal-grid">${goals.slice(0,3).map(g=>goalMini(g)).join('')}</div></section><section class="card"><h2>Conseil ORION</h2><div class="insight"><div class="ico">✨</div><div><b>${t.pct<80?'Budget sous contrôle':'Budget à surveiller'}</b><p>Plus gros poste : ${biggestCat()}.</p></div></div></section>`}
function row(r,type,i){let done=r.paid||isAutoIncome(r);let sign=type==='income'?'+':'-';return `<div class="row ${done?'done':''}" data-toggle="${type}" data-index="${i}"><div class="check">✓</div><div class="row-main"><div class="row-title">${cats[r.cat]?.[1]||''} ${esc(r.name)}</div><div class="row-meta">${done?'Confirmé':'Prévu'} · ${dateFR(r.dueDate)}</div></div><div class="amount ${type==='income'?'pos':'neg'}">${sign}${eur(r.amount)}</div></div>`}
function goalMini(g){let p=Math.min(100,Math.round(cap()/g.target*100));return `<div class="goal-mini"><div class="emoji">${g.e}</div><b>${esc(g.n)}</b><div class="circle" style="--p:${p}%">${p}%</div><small>${eur(cap())} / ${eur(g.target)}</small></div>`}
function biggestCat(){let ct=catTotals(),ks=Object.keys(ct).sort((a,b)=>ct[b]-ct[a]);return ks[0]?(cats[ks[0]]?.[0]||ks[0])+' · '+eur(ct[ks[0]]):'aucune dépense'}
function renderTransactions(){let rows=[...m().income.map((r,i)=>({...r,type:'income',idx:i})),...m().expenses.map((r,i)=>({...r,type:'expense',idx:i}))];let q=($('txSearch')&&$('txSearch').value||'').toLowerCase();rows=rows.filter(r=>(filter==='all'||filter===r.type)&&(!q||r.name.toLowerCase().includes(q)||(cats[r.cat]?.[0]||'').toLowerCase().includes(q)));$('page-transactions').innerHTML=`<section class="card"><div class="list-head"><h2>Transactions</h2><button class="icon-btn" id="addLine">+</button></div><div class="filters"><input class="search" id="txSearch" placeholder="Rechercher" value="${esc(q)}"><select class="month-select" id="monthPick">${ML.map((x,i)=>`<option value="${i}" ${i===month?'selected':''}>${x}</option>`).join('')}</select></div><div class="tabs"><button class="tab ${filter==='all'?'active':''}" data-filter="all">Tout</button><button class="tab ${filter==='income'?'active':''}" data-filter="income">Revenus</button><button class="tab ${filter==='expense'?'active':''}" data-filter="expense">Dépenses</button></div>${rows.map(r=>`<div class="tx-row" data-edit="${r.type}" data-index="${r.idx}"><div class="tx-icon">${r.type==='income'?'✓':(cats[r.cat]?.[1]||'●')}</div><div class="tx-info"><b>${esc(r.name)}</b><p>${r.type==='income'?'Revenu':(cats[r.cat]?.[0]||'Autres')} · ${dateFR(r.dueDate)} · ${r.paid?'confirmé':'prévu'}</p></div><div class="amount ${r.type==='income'?'pos':'neg'}">${r.type==='income'?'+':'-'}${eur(r.amount)}</div></div>`).join('')||'<p class="empty">Aucune ligne.</p>'}</section>`}
function renderStats(){let ct=catTotals(),vals=Object.values(ct),max=Math.max(...vals,1),t=totals(),prev=prevTotals(),diff=t.final-prev.final;$('page-stats').innerHTML=`<section class="card"><h2>Répartition</h2><div class="bars">${Object.keys(ct).sort((a,b)=>ct[b]-ct[a]).map(k=>`<div class="bar-row"><span>${cats[k]?.[0]||k}</span><div class="bar-bg"><span style="width:${ct[k]/max*100}%"></span></div><b>${eur(ct[k])}</b></div>`).join('')||'<p class="empty">Aucune dépense.</p>'}</div></section><section class="card"><h2>Comparaison</h2><div class="insight"><div class="ico">📈</div><div><b>${diff>=0?'+':''}${eur(diff)} vs mois précédent</b><p>Dépenses : ${eur(t.tex)} · Revenus : ${eur(t.tin)}</p></div></div></section><section class="card"><h2>Courbe du mois</h2><div class="spark">${spark()}</div></section>`}
function renderGoals(){$('page-goals').innerHTML=`<section class="card"><div class="list-head"><h2>Objectifs</h2><button class="icon-btn" id="addGoal">+</button></div></section>`+goals.map((g,i)=>goalCard(g,i)).join('')}
function goalCard(g,i){let p=Math.min(100,Math.round(cap()/g.target*100));return `<section class="card goal-card" data-goal="${i}"><div class="big-emoji">${g.e}</div><div class="middle"><h3>${esc(g.n)}</h3><p>${eur(cap())} / ${eur(g.target)}</p><div class="progress"><span style="width:${p}%"></span></div></div><b>${p}%</b></section>`}
function renderSettings(){$('page-settings').innerHTML=`<section class="card settings-area"><h2>Données</h2><button class="primary" id="exportBtn">Exporter JSON</button><br><br><textarea id="jsonArea" placeholder="Export / import JSON"></textarea><br><br><button class="secondary" id="importBtn">Importer JSON</button></section><section class="card"><h2>Infos</h2><div class="insight"><div class="ico">✅</div><div><b>Compatibilité ancienne app</b><p>Lecture automatique de bgt4, budgetV3 et budgetV2.</p></div></div><div class="insight" style="margin-top:12px"><div class="ico">💾</div><div><b>Stockage local</b><p>Les données restent dans le navigateur.</p></div></div></section><section class="card danger-zone"><h2>Maintenance</h2><button class="danger" id="resetDemo">Réinitialiser la démo ORION</button></section>`}
function render(){ $('monthLabel').textContent=ML[month]+' '+new Date().getFullYear(); renderDashboard(); renderTransactions(); renderStats(); renderGoals(); renderSettings(); document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage)); }
function switchPage(p){currentPage=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('page-'+p).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));window.scrollTo({top:0,behavior:'smooth'})}
function openSheet(type='expense',idx=''){let arr=type==='income'?m().income:m().expenses;let r=idx!==''?arr[idx]:mkRow('',0,today(),'autres');$('editIndex').value=idx;setType(type);$('editName').value=r.name;$('editAmount').value=r.amount||'';$('editDate').value=r.dueDate||today();$('editCat').innerHTML=Object.keys(cats).map(k=>`<option value="${k}" ${r.cat===k?'selected':''}>${cats[k][1]} ${cats[k][0]}</option>`).join('');$('editPaid').checked=!!r.paid||isAutoIncome(r);$('btnDelete').style.display=idx===''?'none':'';$('sheetTitle').textContent=idx===''?'Ajouter une ligne':'Modifier la ligne';$('sheetBackdrop').classList.add('open');$('editorSheet').classList.add('open')}
function setType(type){$('editorSheet').dataset.type=type;document.querySelectorAll('#typeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.type===type))}
function closeSheet(){$('sheetBackdrop').classList.remove('open');$('editorSheet').classList.remove('open')}
function saveLine(){let type=$('editorSheet').dataset.type||'expense',idx=$('editIndex').value;let r=mkRow($('editName').value,$('editAmount').value,$('editDate').value,$('editCat').value);r.paid=$('editPaid').checked;r.paidDate=r.paid?today():'';if(!r.name.trim())return alert('Ajoute un libellé');if(type==='income'){if(idx==='')m().income.push(r);else Object.assign(m().income[idx],r)}else{if(idx==='')m().expenses.push(r);else Object.assign(m().expenses[idx],r)}save();render();closeSheet()}
function delLine(){let type=$('editorSheet').dataset.type||'expense',idx=$('editIndex').value;if(idx==='')return;if(!confirm('Supprimer cette ligne ?'))return;if(type==='income')m().income.splice(idx,1);else m().expenses.splice(idx,1);save();render();closeSheet()}
function editGoal(i){let g=goals[i]||{n:'Nouvel objectif',e:'🎯',target:1000};let name=prompt('Nom de l’objectif',g.n);if(name===null)return;let target=Number(prompt('Montant cible',g.target));if(!target)return alert('Montant invalide');g.n=name;g.target=target;goals[i]=g;saveGoals();render()}
function addGoal(){let name=prompt('Nom de l’objectif','Nouveau projet');if(!name)return;let target=Number(prompt('Montant cible','1000'));if(!target)return;goals.push({id:'g'+Date.now(),n:name,e:'🎯',target});saveGoals();render()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.addEventListener('click',e=>{let nav=e.target.closest('.bottom-nav button');if(nav)return switchPage(nav.dataset.page);let go=e.target.closest('[data-page-go]');if(go)return switchPage(go.dataset.pageGo);let f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;renderTransactions();return}let r=e.target.closest('[data-toggle]');if(r){let arr=r.dataset.toggle==='income'?m().income:m().expenses;let item=arr[Number(r.dataset.index)];if(item&&!isAutoIncome(item)){item.paid=!item.paid;item.paidDate=item.paid?today():'';save();render()}return}let ed=e.target.closest('[data-edit]');if(ed)return openSheet(ed.dataset.edit,ed.dataset.index);let gc=e.target.closest('[data-goal]');if(gc)return editGoal(Number(gc.dataset.goal));if(e.target.id==='addGoal')return addGoal();if(e.target.id==='addLine'||e.target.id==='globalAdd')return openSheet('expense','');if(e.target.closest('#typeTabs button'))return setType(e.target.closest('#typeTabs button').dataset.type);if(e.target.id==='btnCloseSheet'||e.target.id==='sheetBackdrop')return closeSheet();if(e.target.id==='btnSaveLine')return saveLine();if(e.target.id==='btnDelete')return delLine();if(e.target.id==='btnRefresh'){app=load();goals=loadGoals();render();return}if(e.target.id==='exportBtn'){$('jsonArea').value=JSON.stringify({app,goals},null,2);return}if(e.target.id==='importBtn'){try{let raw=JSON.parse($('jsonArea').value);app=normalize(raw.app||raw);if(raw.goals)goals=raw.goals;save();saveGoals();render();alert('Import OK')}catch(err){alert('JSON invalide')}}if(e.target.id==='resetDemo'){if(confirm('Recharger les données depuis le stockage ?')){app=load();render()}}});
document.addEventListener('input',e=>{if(e.target.id==='txSearch')renderTransactions()});document.addEventListener('change',e=>{if(e.target.id==='monthPick'){month=Number(e.target.value);app.currentMonth=month;save();render();}});
render();
})();